#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Update our PATH if git-bashrc isn't already in the PATH (idempotent add)
[ "\$PATH" == "\${PATH/git-bashrc/}" ] && export PATH="\$PATH:$SCRIPT_DIR/scripts"

# git branch sorted
alias gbs="git branch --sort=-committerdate"

# tag next quick (and push)
alias tnq='tag-next -q && git push --tags'

# git log (pretty)
alias gl='git log --date=short --pretty=format:"%Cred%h %Cblue%cd %Cgreen%an%Creset %s" -12'

# git log (short)
alias gls='git log --pretty=format:"%Cred%h %Cgreen%an%Creset %s" -12'

# git status
alias gs='git status'

# Todo: make a git alias so this is `git cleanup`
alias git-cleanup='git branch --merged | grep -v "\*" | xargs -n 1 git branch -d'

# Search the HEAD of every local branch for a pattern
function grep-branches()
{
  git grep $1 $(git show-ref --heads) | grep "refs/heads" | grep $1
}
